#ifndef __LUA_HANDLERS_H__
#define __LUA_HANDLERS_H__

#define LUA_ON_INIT "onInit" // ()
#define LUA_ON_DESTROY "onDestroy" // ()
#define LUA_ON_PLAYER_SPAWN "onPlayerSpawn" // (int actor_cn)
#define LUA_ON_PLAYER_CONNECT "onPlayerConnect" // (int actor_cn)
#define LUA_ON_PLAYER_DISCONNECT "onPlayerDisconnect" // (int actor_cn, int reason)
#define LUA_ON_PLAYER_GET_DAMAGE "onPlayerDamage" // (int actor_cn, int target_cn, int damage, int actor_gun, bool gib)
#define LUA_ON_PLAYER_DEATH "onPlayerDeath" // (int target_cn, int actor_cn, bool gib, int gun)
#define LUA_ON_ARENA_WIN "onArenaWin" // (int alive_cn)
#define LUA_ON_MAP_CHANGE "onMapChange" // (string map_name, int game_mode)
#define LUA_ON_MAP_END "onMapEnd" // ()
#define LUA_ON_PLAYER_TEAM_CHANGE "onPlayerTeamChange" // (int actor_cn, int new_team, int forceteam_reason)
#define LUA_ON_SERVER_PROCESS "onServerProcess" // (int sender_cn, int channel, int type)
#define LUA_ON_PLAYER_ITEM_PICKUP "onPlayerItemPickup" // (int actor_cn, int item_type, int item_id)
#define LUA_ON_PLAYER_SAY_TEXT "onPlayerSayText" // (int sender_cn, string message, bool team, bool me)
#define LUA_ON_EXTENSION "onExtension" // (string extension, int sender_cn, string argument)

/// generator since 1.4
#define LUA_ON_PLAYER_CALL_VOTE "onPlayerCallVote" // = int (vote error); (int actor_cn, int type, string text, int number, int vote_error)

#define LUA_ON_PLAYER_SHOOT "onPlayerShoot" // (int actor_cn, int gun, table to)
#define LUA_ON_FLAG_ACTION "onFlagAction" // (int actor_cn, int action, int flag)
#define LUA_ON_LOOP "LuaLoop" // ()
#define LUA_ON_NOTICE "onLuaNotice" // (obj message, string target)
#define LUA_ON_PLAYER_SAY_VOICE "onPlayerSayVoice" // (int actor_cn, int sound)
#define LUA_ON_ITEM_SPAWN "onItemSpawn" // (int item_id, int item_type)
#define LUA_ON_ITEM_RESPAWN "onItemRespawn" // (int item_id, int item_type)
#define LUA_ON_PLAYER_WEAPON_CHANGE "onPlayerWeaponChange" // (int actor_cn, int new_weapon)
#define LUA_ON_PLAYER_NAME_CHANGE "onPlayerNameChange" // (int actor_cn, string new_name)
#define LUA_ON_PLAYER_ROLE_CHANGE "onPlayerRoleChange" // (int actor_cn, int new_role, string hash, int adminpwd_line, bool player_is_connecting)
#define LUA_ON_PLAYER_ROLE_CHANGE_TRY "onPlayerRoleChangeTry" // (int actor_cn, int new_role, string hash, bool player_is_connecting)
#define LUA_ON_MAPROT_READ "onMaprotRead" // ()
#define LUA_ON_PASSWORDS_READ "onPasswordsRead" // ()
#define LUA_ON_BL_READ "onBlRead" // ()
#define LUA_ON_LOG_LINE "onLogLine" // (string logline)
#define LUA_ON_PLAYER_WEAPON_RELOAD "onPlayerWeaponReload" // (int actor_cn, int actor_gun)
#define LUA_ON_VOTE_END "onVoteEnd" // (int result, int owner_cn, int type, string text, int number)
#define LUA_ON_PLAYER_SPAWN_CLIENT_SIDE "onPlayerSpawnClientSide" // (int actor_cn)
#define LUA_ON_PLAYER_SWITCH_SPECT_CN "onPlayerSwitchSpectCn" // (int actor_cn, int spect_cn)
#define LUA_ON_PLAYER_SUICIDE "onPlayerSuicide" // (int actor_cn)
#define LUA_ON_PLAYER_VOTE "onPlayerVote" // (int actor_cn, int vote)

/// generator since 1.5
#define LUA_ON_PLAYER_SEND_MAP "onPlayerSendMap" // (string map_name, int sender_cn, int revision, int mapsize, int cfgsize, int cfgsizegz, int upload_error)

#define LUA_ON_PLAYER_DEATH_AFTER "onPlayerDeathAfter" // (int target_cn, int actor_cn, bool gib, int gun)
#define LUA_ON_PLAYER_SPAWN_AFTER "onPlayerSpawnAfter" // (int actor_cn)
#define LUA_ON_PLAYER_GET_DAMAGE_AFTER "onPlayerDamageAfter" // (int actor_cn, int target_cn, int damage, int actor_gun, bool gib)
#define LUA_ON_PLAYER_TEAM_CHANGE_AFTER "onPlayerTeamChangeAfter" // (int actor_cn, int old_team, int forceteam_reason)
#define LUA_ON_SERVER_PROCESS_AFTER "onServerProcessAfter" // (int sender_cn, int channel, int type)
#define LUA_ON_PLAYER_ITEM_PICKUP_AFTER "onPlayerItemPickupAfter" // (int actor_cn, int item_type, int item_id)
#define LUA_ON_PLAYER_SAY_TEXT_AFTER "onPlayerSayTextAfter" // (int sender_cn, string message)
#define LUA_ON_PLAYER_ROLE_CHANGE_AFTER "onPlayerRoleChangeAfter" // (int actor_cn, int old_role, string hash, int adminpwd_line, bool player_is_connecting)
#define LUA_ON_ITEM_RESPAWN_AFTER "onItemRespawnAfter" // (int item_id, int item_type)
#define LUA_ON_ITEM_SPAWN_AFTER "onItemSpawnAfter" // (int item_id, int item_type)
#define LUA_ON_PLAYER_SAY_VOICE_AFTER "onPlayerSayVoiceAfter" // (int actor_cn, int sound)
#define LUA_ON_VOTE_END_AFTER "onVoteEndAfter" // (int result, int owner_cn, int type, string text, int number)
#define LUA_ON_PLAYER_SEND_MAP_AFTER "onPlayerSendMapAfter" // (string map_name, int sender_cn, int revision, int mapsize, int cfgsize, int cfgsizegz, int upload_error)
#define LUA_ON_WHOIS "onWhois" // (int sender_cn, int target_cn)
#define LUA_ON_WHOIS_AFTER "onWhoisAfter" // (int sender_cn, int target_cn)
#define LUA_ON_PLAYER_DISCONNECT_AFTER "onPlayerDisconnectAfter" // (int actor_cn, int reason)
#define LUA_ON_LOOP_AFTER "LuaLoopAfter" // ()
#define LUA_ON_PLAYER_SHOOT_AFTER "onPlayerShootAfter" // (int actor_cn, int gun, table to)
#define LUA_ON_INIT_AFTER "onInitAfter" // ()
#define LUA_ON_MASTER_SERVER_UPDATE "onMasterServerUpdate" // (string host)
#define LUA_ON_MASTER_SERVER_COMMAND "onMasterServerCommand" // (string host, string command)
#define LUA_ON_MASTER_SERVER_COMMAND_AFTER "onMasterServerCommandAfter" // (string host, string command)
#define LUA_ON_PLAYER_PING_UPDATE "onPlayerPingUpdate" // (int player_cn, int old_ping)
#define LUA_ON_PLAYER_STATE_UPDATE "onPlayerStateUpdate" // (int player_cn)
#define LUA_ON_PLAYER_BAN_THRESHOLD_REACH "onPlayerBanThresholdReach" // (int actor_cn)
#define LUA_ON_PLAYER_KICK_THRESHOLD_REACH "onPlayerKickThresholdReach" // (int actor_cn)
#define LUA_ON_CONFIG_REREAD "onConfigReread" // ()
#define LUA_ON_CONFIG_REREAD_AFTER "onConfigRereadAfter" // ()

/// generator since 1.5
#define LUA_ON_PLAYER_REMOVE_MAP "onPlayerRemoveMap" // (string map_name, int sender_cn, int remove_error)

#define LUA_ON_PLAYER_REMOVE_MAP_AFTER "onPlayerRemoveMapAfter" // (string map_name, int sender_cn, int remove_error)
#define LUA_ON_PLAYER_PRECONNECT "onPlayerPreconnect" // (int actor_cn)
#define LUA_ON_PLAYER_SWITCH_EDITING "onPlayerSwitchEditing" // (int actor_cn, bool is_editing)

#endif
